### ISSUE TITLE
tf.data for GON

### ISSUE THREAD

**Issue by SamuelMarks** [SamuelMarks/ml-glaucoma#3]
Develop [`tf.data`](https://www.tensorflow.org/api_docs/python/tf/data) pipeline for [GON](https://ai.baidu.com/broad/subordinate?dataset=gon), including saving processed file to a useful format (e.g.: [tfrecords](https://www.tensorflow.org/tutorials/load_data/tf_records)).

**Comment by jackd** [comment]
Implemented [here](https://github.com/SamuelMarks/ml-glaucoma/blob/jackd-v2/ml_glaucoma/tfds_builders/refuge.py) - can rename to GON if desired, but link to original names it refuge.

**Comment by jackd** [comment]
If there are issues with checksums, you may need to copy the following into `tensorflow_datasets/url_checksums/refuge.txt` - have raised an [issue](https://github.com/tensorflow/datasets/issues/580), can do a hack until it's fixed.

```
https://aipe-broad-dataset.cdn.bcebos.com/gno/Annotation-Training400.zip 348137626 5dc4b16c5e4c3f7c30106b0f22f0b44b7d4bdc18f12d3a0d2e0cadc41fd8e92b
https://aipe-broad-dataset.cdn.bcebos.com/gno/REFUGE-Test400.zip 360832658 ff8a2f14ec94812186310cbf490a69c6deed9d9377c1f9dd5ba05ee0ff1a99cb
https://aipe-broad-dataset.cdn.bcebos.com/gno/REFUGE-Training400.zip 716807624 c6d4f8cd66b0b558f8f63245803cba53e774ab6c5de9dfb7bd113a6e30fb183a
https://aipe-broad-dataset.cdn.bcebos.com/gno/REFUGE-Validation400-GT.zip 5320597 e535a7bf0ad7bc6e94ffa68f8bda5e4965be0972d31c44f610c60beb3e1a9e84
https://aipe-broad-dataset.cdn.bcebos.com/gno/REFUGE-Validation400.zip 360709102 c47e0fc74c8499bba263b65afe3bbcb66de0d7513c2da1f2118d283c424f48ca
```

**Comment by jackd** [comment]
This is fixed in the master branch of `tfds`, but I've implemented a [hack](https://github.com/SamuelMarks/ml-glaucoma/blob/jackd-v2/ml_glaucoma/tfds_checksums.py) to fix it in earlier official releases.

**Comment by SamuelMarks** [comment]
Surprisingly, updating the [`_sizes_checksums`](https://github.com/tensorflow/datasets/blob/v2.1.0/tensorflow_datasets/core/download/download_manager.py#L241-L243) dictionary of the [`tfds.download.DownloadManager`]( https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager) is sufficient here:
https://github.com/SamuelMarks/ml_prepare/blob/d81a625/ml_prepare/refuge/tfds.py#L82-L97

(not documented usage, and subject to change as it uses a `_` prefixed method)
